export { create_controller as create_blocks_controller } from './blocks.controller'
export { create_controller as create_cycles_controller } from './cycles.controller'
export { create_controller as create_exercises_controller } from './exercises.controller'
export { create_controller as create_sets_controller } from './sets.controller'
export { create_controller as create_workouts_controller } from './workouts.controller'